version: '{build}'
image: Visual Studio 2019
clone_depth: 50

environment:
  plaid___environment: Sandbox
  plaid__clientid:
    secure: LHaNof6xreYofWfu9NxtrzBdzyZGtMEBB4NMQeAIKVQ=
  plaid__secret:
    secure: MCc8PeEdf8QmYIsEGe9B57fVM14HDQbExL9HJFVAhaA=
  plaid__defaultaccesstoken:
    secure: DcAYLk/mgGHvSpR7g+WDjGFTW2VO43sgHEi5RbXJoh4bd2zPzdbmM4m82jA2GHTyqDDFj9eZOmLjd2yvKTzH/w==

before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore --verbosity m

build_script:
  - cmd: dotnet build ./src/Plaid/Plaid.csproj -c Release

test_script:
  - cmd: dotnet test

after_test:
  - cmd: dotnet pack ./src/Plaid/Plaid.csproj -c Release

artifacts:
  - path: '**\*.nupkg'
  - path: '**\*.snupkg'

cache:
  - '%LocalAppData%\NuGet\v3-cache' # NuGet v3

deploy:
  - provider: NuGet
    api_key:
      secure: GJVmu2j1exMpBljCZYYxq0OfX2Ug2TK/GM50LxmJg02jGRVmJJ98kGT/aMoNAwxC
    skip_symbols: false
    artifact: /.*(\.|\.s)nupkg/
    on: 
      APPVEYOR_REPO_TAG: true        # deploy on tag push only

  - provider: GitHub
    auth_token:
      secure: gLjuy01aV234sOjDtHTsqYPwox1c1Qj6uHYSIg0ToLcBDdbGePs30M6Dx/fmFdyX
    name: Release $(APPVEYOR_REPO_TAG_NAME)
    description: Release $(APPVEYOR_REPO_TAG_NAME)
    artifact: /.*(\.|\.s)nupkg/
    on: 
      APPVEYOR_REPO_TAG: true        # deploy on tag push only
