namespace Going.Plaid.Entity;

/// <summary>
/// <para>Object representing metadata pertaining to the document.</para>
/// </summary>
public record CreditDocumentMetadata
{
	/// <summary>
	/// <para>The name of the document.</para>
	/// </summary>
	[JsonPropertyName("name")]
	public string Name { get; init; } = default!;

	/// <summary>
	/// <para>The type of document.</para>
	/// <para><c>PAYSTUB</c>: A paystub.</para>
	/// <para><c>BANK_STATEMENT</c>: A bank statement.</para>
	/// <para><c>US_TAX_W2</c>: A W-2 wage and tax statement provided by a US employer reflecting wages earned by the employee.</para>
	/// <para><c>US_MILITARY_ERAS</c>: An electronic Retirement Account Statement (eRAS) issued by the US military.</para>
	/// <para><c>US_MILITARY_LES</c>: A Leave and Earnings Statement (LES) issued by the US military.</para>
	/// <para><c>US_MILITARY_CLES</c>: A Civilian Leave and Earnings Statment (CLES) issued by the US military.</para>
	/// <para><c>GIG</c>: Used to indicate that the income is related to gig work. Does not necessarily correspond to a specific document type.</para>
	/// <para><c>PLAID_GENERATED_PAYSTUB_PDF</c>: Used to indicate that the PDF for the paystub was generated by Plaid.</para>
	/// <para><c>NONE</c>: Used to indicate that there is no underlying document for the data.</para>
	/// <para><c>UNKNOWN</c>: Document type could not be determined.</para>
	/// </summary>
	[JsonPropertyName("document_type")]
	public string? DocumentType { get; init; } = default!;

	/// <summary>
	/// <para>Signed URL to retrieve the underlying file. This download URL can only be used once and expires after two minutes. To generate a new download URL, call <c>/credit/payroll_income/get</c> again.</para>
	/// </summary>
	[JsonPropertyName("download_url")]
	public string? DownloadUrl { get; init; } = default!;

	/// <summary>
	/// <para>The processing status of the document.</para>
	/// <para><c>PROCESSING_COMPLETE</c>: The document was successfully processed.</para>
	/// <para><c>DOCUMENT_ERROR</c>: The document could not be processed. Possible causes include: The document was an unacceptable document type such as an offer letter or bank statement, the document image was cropped or blurry, or the document was corrupted.</para>
	/// <para><c>UNKNOWN</c> or <c>null</c>: An internal error occurred. If this happens repeatedly, contact support or your Plaid account manager.</para>
	/// </summary>
	[JsonPropertyName("status")]
	public string? Status { get; init; } = default!;

	/// <summary>
	/// <para>The number of pages of the uploaded document (if available).</para>
	/// </summary>
	[JsonPropertyName("page_count")]
	public int? PageCount { get; init; } = default!;
}