namespace Going.Plaid.Entity;

/// <summary>
/// <para>A unique <c>user_id</c> generated by Plaid for the client-provided <c>client_user_id</c>. This field is currently in beta. If both <c>client_user_id</c> and <c>user_id</c> are provided, <c>client_user_id</c> must match the value for the returned user.</para>
/// </summary>
public class IdentityVerificationListRequestUserIdObject
{
}
