namespace Going.Plaid.Entity;

/// <summary>
/// <para>A unique <c>user_id</c> generated by Plaid for the client-provided <c>client_user_id</c>. This field is currently in beta. If this field is provided, <c>client_user_id</c> is ignored.</para>
/// </summary>
public class IdentityVerificationListRequestUserIdObject
{
}
