namespace Going.Plaid.Entity;

/// <summary>
/// <para>Specifies options for initializing Link for use with the CRA Income Insights product.</para>
/// </summary>
public class LinkTokenCreateRequestCraOptionsIncomeInsights
{
	/// <summary>
	/// <para>Filters the returned income streams based on the specified income categories. If no filters are requested, streams from the following default set of categories are returned:</para>
	/// <para>- <c>EARNED_INCOME.*</c> (<c>EARNED_INCOME.SALARY</c>, <c>EARNED_INCOME.GIG_ECONOMY</c>, <c>EARNED_INCOME.SELF_EMPLOYED</c>)</para>
	/// <para>- <c>BENEFITS.DISABILITY</c></para>
	/// <para>- <c>RETIREMENT.*</c> (<c>RETIREMENT.GOVERNMENT_DERIVED</c>, <c>RETIREMENT.PRIVATE_RETIREMENT</c>, <c>RETIREMENT.PLAN_DISTRIBUTION</c>)</para>
	/// <para>The final list of income categories is generated by adding the <c>included_categories</c>, then removing the <c>excluded_categories</c>. Priority is given to <c>excluded_categories</c> in the case of collisions.</para>
	/// <para>Filter patterns supported:</para>
	/// <para>- <c>*</c>: All categories</para>
	/// <para>- <c>PRIMARY.*</c>: All categories within the specified primary category</para>
	/// <para>- <c>PRIMARY.SECONDARY</c>: A specific income category</para>
	/// <para>For a list of income categories, see the <a href="https://plaid.com/documents/income-v2-category-taxonomy.csv">Income V2 Category Taxonomy</a>.</para>
	/// </summary>
	[JsonPropertyName("income_insights_filter")]
	public Entity.IncomeInsightsFilter? IncomeInsightsFilter { get; set; } = default!;

	/// <summary>
	/// <para>The version of Income Insights to use.</para>
	/// </summary>
	[JsonPropertyName("income_insights_version")]
	public Entity.IncomeInsightsVersion? IncomeInsightsVersion { get; set; } = default!;

}
