namespace Going.Plaid.IdentityVerification;

/// <summary>
/// <para>Request input for listing Identity Verifications</para>
/// </summary>
public partial class IdentityVerificationListRequest : RequestBase
{
	/// <summary>
	/// <para>ID of the associated Identity Verification template. Like all Plaid identifiers, this is case-sensitive.</para>
	/// </summary>
	[JsonPropertyName("template_id")]
	public string TemplateId { get; set; } = default!;

	/// <summary>
	/// <para>A unique ID that identifies the end user in your system. This ID can also be used to associate user-specific data from other Plaid products. Financial Account Matching requires this field and the <c>/link/token/create</c> <c>client_user_id</c> to be consistent. Personally identifiable information, such as an email address or phone number, should not be used in the <c>client_user_id</c>.</para>
	/// </summary>
	[JsonPropertyName("client_user_id")]
	public string? ClientUserId { get; set; } = default!;

	/// <summary>
	/// <para>A unique <c>user_id</c> generated by Plaid for the client-provided <c>client_user_id</c>. This field is currently in beta. If both <c>client_user_id</c> and <c>user_id</c> are provided, <c>client_user_id</c> must match the value for the returned user.</para>
	/// </summary>
	[JsonPropertyName("user_id")]
	public Entity.IdentityVerificationListRequestUserIdObject? UserId { get; set; } = default!;

	/// <summary>
	/// <para>An identifier that determines which page of results you receive.</para>
	/// </summary>
	[JsonPropertyName("cursor")]
	public string? Cursor { get; set; } = default!;

}
