namespace Going.Plaid;

public sealed partial class PlaidClient
{
	/// <summary>
	/// <para>The <c>/link/token/create</c> endpoint creates a <c>link_token</c>, which is required as a parameter when initializing Link. Once Link has been initialized, it returns a <c>public_token</c>, which can then be exchanged for an <c>access_token</c> via <c>/item/public_token/exchange</c> as part of the main Link flow.</para>
	/// <para>A <c>link_token</c> generated by <c>/link/token/create</c> is also used to initialize other Link flows, such as the update mode flow for tokens with expired credentials, or the Payment Initiation (Europe) flow.</para>
	/// </summary>
	/// <remarks><see href="https://plaid.com/docs/api/tokens/#linktokencreate" /></remarks>
	public Task<Link.LinkTokenCreateResponse> LinkTokenCreateAsync(Link.LinkTokenCreateRequest request) =>
		PostAsync("/link/token/create", request)
			.ParseResponseAsync<Link.LinkTokenCreateResponse>();

	/// <summary>
	/// <para>The <c>/link/token/get</c> endpoint gets information about a previously-created <c>link_token</c> using the</para>
	/// <para><c>/link/token/create</c> endpoint. It can be useful for debugging purposes.</para>
	/// </summary>
	/// <remarks><see href="https://plaid.com/docs/api/tokens/#linktokenget" /></remarks>
	public Task<Link.LinkTokenGetResponse> LinkTokenGetAsync(Link.LinkTokenGetRequest request) =>
		PostAsync("/link/token/get", request)
			.ParseResponseAsync<Link.LinkTokenGetResponse>();
}