namespace Going.Plaid;

public sealed partial class PlaidClient
{
	/// <summary>
	/// <para>The <c>/link/profile/eligibility/check</c> endpoint can be used to check whether a user with the</para>
	/// <para>supplied phone number has a saved profile that satisfies customer-defined eligibility</para>
	/// <para>requirements.</para>
	/// </summary>
	/// <remarks><see href="https://plaid.com/docs/api/link/#profileeligibilitycheck" /></remarks>
	public Task<Link.LinkProfileEligibilityCheckResponse> LinkProfileEligibilityCheckAsync(Link.LinkProfileEligibilityCheckRequest request) =>
		PostAsync("/link/profile/eligibility/check", request)
			.ParseResponseAsync<Link.LinkProfileEligibilityCheckResponse>();

	/// <summary>
	/// <para>The <c>/link/token/create</c> endpoint creates a <c>link_token</c>, which is required as a parameter when initializing Link. Once Link has been initialized, it returns a <c>public_token</c>. For most Plaid products, the <c>public_token</c> is saved and exchanged for an <c>access_token</c> via <c>/item/public_token/exchange</c> as part of the main Link flow. For more details, see the <a href="https://plaid.com/docs/link/#link-flow-overview">Link flow overview</a>.</para>
	/// <para>A <c>link_token</c> generated by <c>/link/token/create</c> is also used to initialize other Link flows, such as the <a href="https://plaid.com/docs/link/update-mode">update mode</a> flow for tokens with expired credentials, or the Identity Verification flow.</para>
	/// </summary>
	/// <remarks><see href="https://plaid.com/docs/api/link/#linktokencreate" /></remarks>
	public Task<Link.LinkTokenCreateResponse> LinkTokenCreateAsync(Link.LinkTokenCreateRequest request) =>
		PostAsync("/link/token/create", request)
			.ParseResponseAsync<Link.LinkTokenCreateResponse>();

	/// <summary>
	/// <para>The <c>/link/token/get</c> endpoint gets information about a Link session, including all callbacks fired during the session along with their metadata, including the public token. This endpoint is used with Link flows that don't provide a public token via frontend callbacks, such as the <a href="https://plaid.com/docs/link/hosted-link/">Hosted Link flow</a> and the <a href="https://plaid.com/docs/link/multi-item-link/">Multi-Item Link flow</a>. It also can be useful for debugging purposes.</para>
	/// </summary>
	/// <remarks><see href="https://plaid.com/docs/api/link/#linktokenget" /></remarks>
	public Task<Link.LinkTokenGetResponse> LinkTokenGetAsync(Link.LinkTokenGetRequest request) =>
		PostAsync("/link/token/get", request)
			.ParseResponseAsync<Link.LinkTokenGetResponse>();

	/// <summary>
	/// <para>Exchange an OAuth <c>link_correlation_id</c> for the corresponding <c>link_token</c>. The <c>link_correlation_id</c> is only available for 'payment_initiation' products and is provided to the client via the OAuth <c>redirect_uri</c> as a query parameter.</para>
	/// <para>The <c>link_correlation_id</c> is ephemeral and expires in a brief period, after which it can no longer be exchanged for the 'link_token'.</para>
	/// </summary>
	/// <remarks><see href="https://plaid.com/docs/api/oauth/#linkcorrelationid" /></remarks>
	public Task<Link.LinkOAuthCorrelationIdExchangeResponse> LinkOauthCorrelationIdExchangeAsync(Link.LinkOAuthCorrelationIdExchangeRequest request) =>
		PostAsync("/link/oauth/correlation_id/exchange", request)
			.ParseResponseAsync<Link.LinkOAuthCorrelationIdExchangeResponse>();

}
