namespace Going.Plaid.Profile;

/// <summary>
/// <para>ProfileGetRequest defines the request schema for <c>/profile/get</c></para>
/// </summary>
public partial class ProfileGetRequest : RequestBase
{
	/// <summary>
	/// <para>The profile token generated by the end user authorization session.</para>
	/// </summary>
	[JsonPropertyName("profile_token")]
	public string ProfileToken { get; set; } = default!;

}
