namespace Going.Plaid.Cra;

/// <summary>
/// <para>CraCheckReportVerificationGetRequest defines the request schema for <c>/cra/check_report/verification/get</c>.</para>
/// </summary>
public partial class CraCheckReportVerificationGetRequest : RequestBase
{
	/// <summary>
	/// <para>Specifies which types of verification reports are expected in the response</para>
	/// </summary>
	[JsonPropertyName("reports_requested")]
	public IReadOnlyList<Entity.CraCheckReportVerificationGetReportType> ReportsRequested { get; set; } = default!;

	/// <summary>
	/// <para>Defines configuration options for the Employment Refresh Report.</para>
	/// </summary>
	[JsonPropertyName("employment_refresh_options")]
	public Entity.CraCheckReportVerificationGetEmploymentRefreshOptions? EmploymentRefreshOptions { get; set; } = default!;

	/// <summary>
	/// <para>The user token associated with the User data is being requested for.</para>
	/// </summary>
	[JsonPropertyName("user_token")]
	public string? UserToken { get; set; } = default!;

	/// <summary>
	/// <para>A unique ID generated by Plaid representing the end user. Typically, this ID will come from the <c>/user/create</c> response, when the endpoint is invoked with the <c>PLAID-NEW-USER-API-ENABLED</c> header. If this field is included, then the <c>user_token</c> object field is ignored.</para>
	/// </summary>
	[JsonPropertyName("user_id")]
	public string? UserId { get; set; } = default!;

}
