namespace Going.Plaid.Cra;

/// <summary>
/// <para>CraMonitoringInsightsSubscribeRequest defines the request schema for <c>/cra/monitoring_insights/subscribe</c></para>
/// </summary>
public partial class CraMonitoringInsightsSubscribeRequest : RequestBase
{
	/// <summary>
	/// <para>The user token associated with the User data is being requested for.</para>
	/// </summary>
	[JsonPropertyName("user_token")]
	public string UserToken { get; set; } = default!;

	/// <summary>
	/// <para>The item ID to subscribe for Cash Flow Updates.</para>
	/// </summary>
	[JsonPropertyName("item_id")]
	public string? ItemId { get; set; } = default!;

	/// <summary>
	/// <para>A unique ID generated by Plaid representing the end user. Typically, this ID will come from the <c>/user/create</c> response, when the endpoint is invoked with the <c>with_upgraded_user</c> request field set to <c>true</c>. If this field is included, then the <c>user_token</c> object field is ignored.</para>
	/// </summary>
	[JsonPropertyName("user_id")]
	public string? UserId { get; set; } = default!;

	/// <summary>
	/// <para>URL to which Plaid will send Cash Flow Updates webhooks, for example when the requested Cash Flow Updates report is ready.</para>
	/// </summary>
	[JsonPropertyName("webhook")]
	public string Webhook { get; set; } = default!;

	/// <summary>
	/// <para>Income categories to include in Cash Flow Updates. If empty or <c>null</c>, this field will default to including all possible categories.</para>
	/// </summary>
	[JsonPropertyName("income_categories")]
	public IReadOnlyList<Entity.CreditBankIncomeCategory>? IncomeCategories { get; set; } = default!;

}
