namespace Going.Plaid.Sandbox;

/// <summary>
/// <para>SandboxCraCashflowUpdatesUpdateRequest defines the request schema for <c>/sandbox/cashflow_updates/update</c></para>
/// </summary>
public partial class SandboxCraCashflowUpdatesUpdateRequest : RequestBase
{
	/// <summary>
	/// <para>The user token associated with the User data is being requested for.</para>
	/// </summary>
	[JsonPropertyName("user_token")]
	public string? UserToken { get; set; } = default!;

	/// <summary>
	/// <para>A unique ID generated by Plaid representing the end user. Typically, this ID will come from the <c>/user/create</c> response, when the endpoint is invoked with the <c>with_upgraded_user</c> request field set to <c>true</c>. If this field is included, then the <c>user_token</c> object field is ignored.</para>
	/// </summary>
	[JsonPropertyName("user_id")]
	public string? UserId { get; set; } = default!;

	/// <summary>
	/// <para>Webhook codes corresponding to the Cash Flow Updates events to be simulated.</para>
	/// </summary>
	[JsonPropertyName("webhook_codes")]
	public IReadOnlyList<Entity.CashFlowUpdatesEventWebhookCodes>? WebhookCodes { get; set; } = default!;

}
