namespace Going.Plaid.UserAccount;

/// <summary>
/// <para>UserAccountSessionGetRequest defines the request schema for <c>/user_account/session/get</c></para>
/// </summary>
public partial class UserAccountSessionGetRequest : RequestBase
{
	/// <summary>
	/// <para>The public token generated by the end user Layer session.</para>
	/// </summary>
	[JsonPropertyName("public_token")]
	public string PublicToken { get; set; } = default!;

}
