namespace Going.Plaid.Webhook;

/// <summary>
/// <para>For each item on an enabled user, this webhook will fire up to four times a day with status information. This webhook will not fire immediately upon enrollment in Cash Flow Updates. The payload may contain an <c>insights</c> array with insights that have been detected, if any (e.g. <c>LOW_BALANCE_DETECTED</c>, <c>LARGE_DEPOSIT_DETECTED</c>). Upon receiving the webhook, call <c>/cra/monitoring_insights/get</c> to retrieve the updated insights.</para>
/// </summary>
public record CashFlowUpdatesInsightsV2Webhook : WebhookBase
{
	/// <inheritdoc />
	[JsonPropertyName("webhook_type")]
	public override WebhookType WebhookType => WebhookType.CashFlowUpdates;

	/// <inheritdoc />
	[JsonPropertyName("webhook_code")]
	public override WebhookCode WebhookCode => WebhookCode.CashFlowInsightsUpdated;

	/// <summary>
	/// <para>Enum for the status of the insights</para>
	/// </summary>
	[JsonPropertyName("status")]
	public Entity.MonitoringInsightsStatus Status { get; init; } = default!;

	/// <summary>
	/// <para>A unique ID generated by Plaid representing the end user. Typically, this ID will come from the <c>/user/create</c> response, when the endpoint is invoked with the <c>with_upgraded_user</c> request field set to <c>true</c>.</para>
	/// </summary>
	[JsonPropertyName("user_id")]
	public string UserId { get; init; } = default!;

	/// <summary>
	/// <para>Array containing the insights detected within the generated report, if any. Possible values include:</para>
	/// <para>  <c>LARGE_DEPOSIT_DETECTED</c>: signaling a deposit over $5,000</para>
	/// <para>  <c>LOW_BALANCE_DETECTED</c>: signaling a balance below $100</para>
	/// <para>  <c>NEW_LOAN_PAYMENT_DETECTED</c>: signaling a new loan payment</para>
	/// <para>  <c>NSF_OVERDRAFT_DETECTED</c>: signaling an NSF overdraft</para>
	/// </summary>
	[JsonPropertyName("insights")]
	public IReadOnlyList<Entity.CashFlowInsight> Insights { get; init; } = default!;

}
