namespace Going.Plaid.Webhook;

/// <summary>
/// <para>Contains the state of a completed Link session, along with the public token(s) if available.</para>
/// <para>By default, the <c>SESSION_FINISHED</c> webhook is enabled only for clients that are enabled for Hosted Link, or in sessions that are enabled for Multi-Item Link. If you would like to receive this webhook and are not using Hosted Link or Multi-Item Link, contact your Account Manager.</para>
/// </summary>
public record LinkSessionFinishedWebhook : WebhookBase
{
	/// <inheritdoc />
	[JsonPropertyName("webhook_type")]
	public override WebhookType WebhookType => WebhookType.Link;

	/// <inheritdoc />
	[JsonPropertyName("webhook_code")]
	public override WebhookCode WebhookCode => WebhookCode.SessionFinished;

	/// <summary>
	/// <para>The final status of the Link session. Will always be "SUCCESS" or "EXITED".</para>
	/// </summary>
	[JsonPropertyName("status")]
	public string Status { get; init; } = default!;

	/// <summary>
	/// <para>The identifier for the Link session.</para>
	/// </summary>
	[JsonPropertyName("link_session_id")]
	public string LinkSessionId { get; init; } = default!;

	/// <summary>
	/// <para>The link token used to create the Link session.</para>
	/// </summary>
	[JsonPropertyName("link_token")]
	public string LinkToken { get; init; } = default!;

	/// <summary>
	/// <para>The public token generated by the Link session. This field has been deprecated; please use <c>public_tokens</c> instead.</para>
	/// </summary>
	[JsonPropertyName("public_token")]
	public string? PublicToken { get; init; } = default!;

	/// <summary>
	/// <para>The public tokens generated by the Link session.</para>
	/// </summary>
	[JsonPropertyName("public_tokens")]
	public IReadOnlyList<string>? PublicTokens { get; init; } = default!;

}
