namespace Going.Plaid.Webhook;

/// <summary>
/// <para>Contains the state of a completed Link session, along with the public token if available.</para>
/// </summary>
public record LinkSessionFinishedWebhook : WebhookBase
{
	/// <inheritdoc />
	[JsonPropertyName("webhook_type")]
	public override WebhookType WebhookType => WebhookType.Link;

	/// <inheritdoc />
	[JsonPropertyName("webhook_code")]
	public override WebhookCode WebhookCode => WebhookCode.SessionFinished;

	/// <summary>
	/// <para>The final status of the Link session. Will always be "SUCCESS" or "EXITED".</para>
	/// </summary>
	[JsonPropertyName("status")]
	public string Status { get; init; } = default!;

	/// <summary>
	/// <para>The identifier for the Link session.</para>
	/// </summary>
	[JsonPropertyName("link_session_id")]
	public string LinkSessionId { get; init; } = default!;

	/// <summary>
	/// <para>The link token used to create the Link session.</para>
	/// </summary>
	[JsonPropertyName("link_token")]
	public string LinkToken { get; init; } = default!;

	/// <summary>
	/// <para>The public token generated by the Link session.</para>
	/// </summary>
	[JsonPropertyName("public_token")]
	public string? PublicToken { get; init; } = default!;

}
