namespace Going.Plaid.User;

/// <summary>
/// <para>UserProductsTerminateRequest defines the request schema for <c>/user/products/terminate</c></para>
/// </summary>
public partial class UserProductsTerminateRequest : RequestBase
{
	/// <summary>
	/// <para>A unique <c>user_id</c> generated by Plaid for the client-provided <c>client_user_id</c>. This field is currently in beta.</para>
	/// </summary>
	[JsonPropertyName("user_id")]
	public string UserId { get; set; } = default!;

	/// <summary>
	/// <para>An optional list of user-based products to terminate. If not provided, all user-based products will be terminated.</para>
	/// </summary>
	[JsonPropertyName("products")]
	public IReadOnlyList<Entity.UserBasedProducts>? Products { get; set; } = default!;

}
