namespace Going.Plaid.User;

/// <summary>
/// <para>UserItemsAssociateRequest defines the request schema for <c>/user/items/associate</c></para>
/// </summary>
public partial class UserItemsAssociateRequest : RequestBase
{
	/// <summary>
	/// <para>A unique <c>user_id</c> generated by Plaid for the client-provided <c>client_user_id</c>. This field is currently in beta.</para>
	/// </summary>
	[JsonPropertyName("user_id")]
	public string UserId { get; set; } = default!;

	/// <summary>
	/// <para>An array of <c>item_id</c>s to be associated with the <c>user_id</c>.</para>
	/// </summary>
	[JsonPropertyName("item_ids")]
	public IReadOnlyList<string> ItemIds { get; set; } = default!;

}
