namespace Going.Plaid.User;

/// <summary>
/// <para>UserGetRequest defines the request schema for <c>/user/get</c>.</para>
/// </summary>
public partial class UserGetRequest : RequestBase
{
	/// <summary>
	/// <para>A unique <c>user_id</c> generated by Plaid for the client-provided <c>client_user_id</c>. This field is currently in beta.</para>
	/// </summary>
	[JsonPropertyName("user_id")]
	public string UserId { get; set; } = default!;

}
