namespace Going.Plaid.User;

/// <summary>
/// <para>UserItemsListRequest defines the request schema for <c>/user/items/list</c></para>
/// </summary>
public partial class UserItemsListRequest : RequestBase
{
	/// <summary>
	/// <para>A unique <c>user_id</c> generated by Plaid for the client-provided <c>client_user_id</c>. This field is currently in beta.</para>
	/// </summary>
	[JsonPropertyName("user_id")]
	public string UserId { get; set; } = default!;

	/// <summary>
	/// <para>An identifier that can be used to retrieve the next set of Items. The <c>/user/items/list</c> response will contain a <c>next_cursor</c> field if the user has additional Items that were not returned.</para>
	/// </summary>
	[JsonPropertyName("cursor")]
	public string? Cursor { get; set; } = default!;

	/// <summary>
	/// <para>The maximum number of Items to return in the response. If not specified, defaults to 100.</para>
	/// </summary>
	[JsonPropertyName("limit")]
	public int? Limit { get; set; } = default!;

}
