namespace Going.Plaid.Tch;

/// <summary>
/// <para>Provides the fields of a notification response</para>
/// </summary>
public record TCHNotificationResponse : ResponseBase
{
	/// <summary>
	/// <para>Unique message identifier (GUID v4 format) of this command. It is used for the tracking purpose. Each request and its response have same value.</para>
	/// </summary>
	[JsonPropertyName("messageId")]
	public string Messageid { get; init; } = default!;

	/// <summary>
	/// <para>Message identifier assigned for the entire conversation (GUID v4 format). Typically, it is generated by the initiator of the flow. The response has the same value with its request.</para>
	/// </summary>
	[JsonPropertyName("conversationId")]
	public string Conversationid { get; init; } = default!;

	/// <summary>
	/// <para>The five digit status code.</para>
	/// </summary>
	[JsonPropertyName("statusCode")]
	public string? Statuscode { get; init; } = default!;

	/// <summary>
	/// <para>Human readable comments about the status.</para>
	/// </summary>
	[JsonPropertyName("statusMessage")]
	public string? Statusmessage { get; init; } = default!;

}
