namespace Going.Plaid.Tch;

/// <summary>
/// <para>Provides the fields of a notification</para>
/// </summary>
public partial class TCHNotification : RequestBase
{
	/// <summary>
	/// <para>Unique message identifier (GUID v4 format) of this command, used for tracking purposes. Each request and its response have the same value.</para>
	/// </summary>
	[JsonPropertyName("messageId")]
	public string Messageid { get; set; } = default!;

	/// <summary>
	/// <para>Message identifier assigned for the entire conversation (GUID v4 format). Typically, it is generated by the initiator of the flow. The response has the same value with its request.</para>
	/// </summary>
	[JsonPropertyName("conversationId")]
	public string Conversationid { get; set; } = default!;

	/// <summary>
	/// <para>Token requestor identifier associated to the domain to which the token belongs.</para>
	/// </summary>
	[JsonPropertyName("tokenRequestorId")]
	public string? Tokenrequestorid { get; set; } = default!;

	/// <summary>
	/// <para>Unique reference identifier for the token generated.</para>
	/// </summary>
	[JsonPropertyName("tokenReferenceId")]
	public string? Tokenreferenceid { get; set; } = default!;

	/// <summary>
	/// <para>The event timestamp of the last state change.</para>
	/// </summary>
	[JsonPropertyName("tokenTimestamp")]
	public DateTimeOffset? Tokentimestamp { get; set; } = default!;

}
